import 'package:email_validator/email_validator.dart';
// import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:project1/ViewControllers/HomePage.dart';
import 'package:project1/bloc/blocs.dart';
import 'package:project1/bloc/perintah_bloc.dart';
import 'package:project1/shared/shared.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:convert';
import 'package:project1/models/models.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:project1/ui/widgets/widgets.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_html/flutter_html.dart';

import '../../bloc/blocs.dart';
import '../../models/models.dart';
import 'package:audioplayers/audioplayers.dart';

import 'package:bubble/bubble.dart';

part 'sign_in.dart';
part 'splash.dart';
part 'sign_up.dart';
part 'main/onboarding_screen.dart';
part 'main_page.dart';
part 'main/user_account.dart';
part 'main/rate.dart';
part 'main/goals.dart';
part 'main/bydoing.dart';
part 'main/task.dart';
// part 'modal_trigger.dart';
part 'main/product.dart';
part 'detail_product.dart';

part 'detail_materi_mindfull.dart';
part 'detail_materi_pwb.dart';
part 'detail_materi_komunikasi.dart';
part 'wrapper.dart';
part 'home.dart';
part 'detail_materi.dart';
part 'main/success.dart';
part 'main/question_answer.dart';
part 'main/rate_only.dart';
part 'main/mood_only.dart';
part 'main/pop_up.dart';
part 'main/bydoing_audio.dart';
part 'main/materi_detail_task.dart';
part 'home2.dart';

part 'main/choices_quiz.dart';
part 'main/question_answer_upit.dart';
part 'mindfull/sadar.dart';
part 'mindfull/mengamati.dart';
part 'mindfull/kalender.dart';
part 'mindfull/perspektif.dart';
part 'mindfull/kesimpulan.dart';
part 'mindfull/tahukah.dart';
part 'mindfull/suara.dart';
part 'mindfull/perkataan.dart';
