import 'package:email_validator/email_validator.dart';
// import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:project1/ViewControllers/HomePage.dart';
import 'package:project1/bloc/blocs.dart';
import 'package:project1/bloc/perintah_bloc.dart';
import 'package:project1/shared/shared.dart';
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:convert';
import 'package:project1/models/models.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:project1/ui/widgets/widgets.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_html/flutter_html.dart';

import '../../bloc/blocs.dart';
import '../../models/models.dart';
import 'package:audioplayers/audioplayers.dart';

part 'sign_in.dart';
part 'splash.dart';
part 'sign_up.dart';
part 'onboarding_screen.dart';
part 'main_page.dart';
part 'user_account.dart';
part 'rate.dart';
part 'goals.dart';
part 'bydoing.dart';
part 'task.dart';
// part 'modal_trigger.dart';
part 'product.dart';
part 'detail_product.dart';

part 'detail_materi_mindfull.dart';
part 'detail_materi_pwb.dart';
part 'detail_materi_komunikasi.dart';
part 'wrapper.dart';
part 'home.dart';
part 'detail_materi.dart';
part 'success.dart';
part 'question_answer.dart';
part 'rate_only.dart';
part 'mood_only.dart';
part 'pop_up.dart';
part 'bydoing_audio.dart';
part 'materi_detail_task.dart';
